---
# Versions
alpine_release: "3.24"
alpine_repo_mirror: "https://dl-3.alpinelinux.org/"

beets_pip_version: "26.1.2"
beets_setuptools_version: "81"
beets_llvm_version: "20"

gateway_clang_version: "22"

########################

tailnet_dns: dingo-fish.ts.net

timezone: America/New_York

# hostnames
gateway_hostname: pi
server_hostname: dl

# addresses
subnet: 192.168.50.0/24
gateway_subnet_ip: 192.168.50.1
server_subnet_ip: 192.168.50.2

# ports
server_internal_ssh_port: 22
server_external_ssh_port: 2223

immich_port: 2283
navidrome_port: 4533
paperless_port: 8000
m2web_port: 8002
anki_port: 8070
jellyfin_port: 8096

qbittorrent_webui_port: 8090
qbittorrent_torrent_port: 50090
