---
wan_iface: wlan0
lan_iface: eth0

gateway_user: rasp
desktop_dwl_release: "0.8"
desktop_dwl_git_url: "https://codeberg.org/dwl/dwl/releases/download/v0.8/dwl-v0.8.tar.gz"

gateway_dirs:
  zotero:
    path: "/home/{{ gateway_user }}/Zotero"
    owner: "{{ gateway_user }}"
    group: "{{ gateway_user }}"
    mode: "0700"
    recurse: true
  pic:
    path: "/home/{{ gateway_user }}/pic"
    owner: "{{ gateway_user }}"
    group: "{{ gateway_user }}"
    mode: "0700"
    recurse: true
  input_pic:
    path: "/home/{{ gateway_user }}/input_pic"
    owner: "{{ gateway_user }}"
    group: "{{ gateway_user }}"
    mode: "0700"
    recurse: true
