---
## versions ##
beets_pip_version: "26.0.1"

## MAKE SURE THESE ARE CORRECT DRIVES ##
zfs_pool_devices: "{{ ['sdb', 'sdc', 'sdd', 'sde'] if debug | bool else ['sda', 'sdb'] }}"

## Groups ## 
main_user_groups:
  - wheel
  - audio
  - input
  - video
  - netdev
  - musicmedia
  - vidmedia
  - picmedia
  - othermedia
  - stacks
  - m2webdata

server_groups:
  - musicmedia
  - vidmedia
  - picmedia
  - othermedia
  - stacks
  - m2webdata

stacks_group: stacks

## Users ## 
service_users:
  anki:
    name: anki
  paperless:
    name: paperless
  qbittorrent:
    name: qbittorrent
  jellyfin:
    name: jellyfin
  navidrome:
    name: navidrome
  immich:
    name: immich

## URLS ##
immich_compose_file_url: "https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml"

paperless_compose_file_url: "https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/refs/heads/main/docker/compose/docker-compose.sqlite-tika.yml"
paperless_compose_env_file_url: "https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/refs/heads/main/docker/compose/docker-compose.env"
paperless_env_file_url: "https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/refs/heads/main/docker/compose/.env"

## Directories ##
docker_compose_dir: /opt/stacks

external_mount: /mnt/data

internal_dirs:
  main_config:
    path: "/home/{{ main_user }}/.config"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: "0700"
    recurse: true
  srv:
    path: /srv
    owner: root
    group: root
    mode: "0755"
    recurse: false
  stacks:
    path: /opt/stacks
    owner: root
    group: stacks
    mode: "0750"
    recurse: false
  immich_srv_dir:
    path: /srv/immich
    owner: "{{ service_users['immich']['name'] }}"
    group: "{{ service_users['immich']['name'] }}"
    mode: "0750"
    recurse: true
  navidrome_srv_dir:
    path: /srv/navidrome
    owner: "{{ service_users['navidrome']['name'] }}"
    group: "{{ service_users['navidrome']['name'] }}"
    mode: "0750"
    recurse: true
  paperless_srv_dir:
    path: /srv/paperless
    owner: "{{ service_users['paperless']['name'] }}"
    group: "{{ service_users['paperless']['name'] }}"
    mode: "700"
    recurse: true
  paperless_srv_data_dir:
    path: /srv/paperless/data
    owner: "{{ service_users['paperless']['name'] }}"
    group: "{{ service_users['paperless']['name'] }}"
    mode: "700"
    recurse: true
  paperless_srv_media_dir:
    path: /srv/paperless/media
    owner: "{{ service_users['paperless']['name'] }}"
    group: "{{ service_users['paperless']['name'] }}"
    mode: "700"
    recurse: true
  paperless_srv_export_dir:
    path: /srv/paperless/export
    owner: "{{ service_users['paperless']['name'] }}"
    group: "{{ service_users['paperless']['name'] }}"
    mode: "700"
    recurse: true
  paperless_srv_consume_dir:
    path: /srv/paperless/consume
    owner: "{{ service_users['paperless']['name'] }}"
    group: "{{ service_users['paperless']['name'] }}"
    mode: "700"
    recurse: true
  jellyfin_srv_dir:
    path: /srv/jellyfin
    owner: "{{ service_users['jellyfin']['name'] }}"
    group: "{{ service_users['jellyfin']['name'] }}"
    mode: "0750"
    recurse: true
  jellyfin_srv_config_dir:
    path: "/srv/jellyfin/config"
    owner: "{{ service_users['jellyfin']['name'] }}"
    group: "{{ service_users['jellyfin']['name'] }}"
    mode: "0700"
    recurse: true
  jellyfin_srv_cache_dir:
    path: /srv/jellyfin/cache
    owner: "{{ service_users['jellyfin']['name'] }}"
    group: "{{ service_users['jellyfin']['name'] }}"
    mode: "0700"
    recurse: true


external_dirs:
  vid:
    path: "{{ external_mount }}/vid"
    owner: qbittorrent
    group: vidmedia
    mode: "0750"
    recurse: false
  vid_live:
    path: "{{ external_mount }}/vid/live"
    owner: qbittorrent
    group: vidmedia
    mode: "0750"
    recurse: true
  vid_animated:
    path: "{{ external_mount }}/vid/animated"
    owner: qbittorrent
    group: vidmedia
    mode: "0750"
    recurse: true
  vid_key:
    path: "{{ external_mount }}/vid/key"
    owner: qbittorrent
    group: vidmedia
    mode: "0750"
    recurse: true
  vid_show:
    path: "{{ external_mount }}/vid/show"
    owner: qbittorrent
    group: vidmedia
    mode: "0750"
    recurse: true
  pic:
    path: "{{ external_mount }}/pic"
    owner: "{{ main_user }}"
    group: picmedia
    mode: "0750"
    recurse: true
  music:
    path: "{{ external_mount }}/music"
    owner: "{{ main_user }}"
    group: musicmedia
    mode: "0750"
    recurse: false
  music_untagged:
    path: "{{ external_mount }}/music/untagged"
    owner: qbittorrent
    group: musicmedia
    mode: "0750"
    recurse: true
  music_tagged:
    path: "{{ external_mount }}/music/tagged"
    owner: "{{ main_user }}"
    group: musicmedia
    mode: "0750"
    recurse: true
  other:
    path: "{{ external_mount }}/other"
    owner: qbittorrent
    group: othermedia
    mode: "0750"
    recurse: true
  qtmp:
    path: "{{ external_mount }}/qtmp"
    owner: qbittorrent
    group: qbittorrent
    mode: "0700"
    recurse: true
  beets:
    path: "{{ external_mount }}/beets"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: "0700"
    recurse: false
  immich_data:
    path: "{{ external_mount }}/immich_data"
    owner: immich
    group: immich
    mode: "0700"
    recurse: false

## Volumes ##
immich_volumes:
  pic:
    host: "{{ external_dirs['pic']['path'] }}"
    dest: "{{ external_dirs['pic']['path'] }}"
    flags: ":ro"

jellyfin_volumes:
  config:
    host: "{{ internal_dirs['jellyfin_srv_config_dir']['path'] }}"
    dest: /config
    flags: ""
  cache:
    host: "{{ internal_dirs['jellyfin_srv_cache_dir']['path'] }}"
    dest: /cache
    flags: ""
  vid:
    host: "{{ external_dirs['vid']['path'] }}"
    dest: /vid
    flags: ":ro"

navidrome_volumes:
  data:
    host: "{{ internal_dirs['navidrome_srv_dir']['path'] }}"
    dest: /data
    flags: ""
  musid:
    host: "{{ external_dirs['music_tagged']['path'] }}"
    dest: /music
    flags: ":ro"


## ZFS Options ##
zfs_pool_name: data
zfs_pool_mountpoint: "{{ external_mount }}"
zfs_pool_mode:
zfs_pool_state: present
zfs_pool_options:
  - "ashift=12"
zfs_boot_services:
  - zfs-import
  - zfs-mount
  - zfs-load-key
zfs_default_services:
  - zfs-zed
