---
- name: Sync with gateway
  hosts: gateway
  become: true

  tasks:
    - name: Pull input pics
      ansible.posix.synchronize:
        mode: pull
        src: "{{ gateway_dirs['input_pic']['path'] }}/"
        dest: "{{ tk_unsorted_pic_dir }}"
        recursive: true
        delete: false
    - name: Clear input pics
      ansible.builtin.file:
        state: "{{ item }}"
        path: "{{ gateway_dirs['input_pic']['path'] }}"
        owner: "{{ gateway_dirs['input_pic']['owner'] }}"
        group: "{{ gateway_dirs['input_pic']['group'] }}"
        mode: "{{ gateway_dirs['input_pic']['mode'] }}"
      with_items:
        - absent
        - directory
    - name: Sync pics
      ansible.posix.synchronize:
        src: "{{ tk_pic_dir }}/"
        dest: "{{ gateway_dirs['pic']['path'] }}"
        rsync_opts: '--exclude ".*"'
        recursive: true
        delete: true
    - name: Sync Zotero files
      ansible.posix.synchronize:
        src: "{{ tk_zotero_dir }}/"
        dest: "{{ gateway_dirs['zotero']['path'] }}"
        recursive: true
        delete: true

- name: Sync with server
  hosts: server
  become: true

  tasks:
    - name: Sync pictures
      ansible.posix.synchronize:
        src: "{{ tk_pic_dir }}"
        dest: "{{ server_external_dirs['pic']['path'] }}"
        rsync_opts: '--exclude ".*"'
        recursive: true
        delete: true

    - name: Sync m2 files
      ansible.posix.synchronize:
        src: "{{ tk_m2_dir }}/"
        dest: "{{ server_internal_dirs['m2web_srv_dir']['path'] }}"
        rsync_opts: '--exclude ".git" --exclude ".gitignore"'
        recursive: true
        delete: true
        group: false
        times: false
        perms: false
