---
- name: Install dcron
  ansible.builtin.package:
    name: dcron
    state: present

- name: Template in crontabs file
  ansible.builtin.template:
    src: dcron_crontabs.j2
    dest: /tmp/crontabs
    owner: root
    group: root
    mode: "0700"

- name: Template all hourly tasks
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/periodic/hourly/{{ item | basename | splitext | first }}"
    owner: root
    group: root
    mode: "0700"
  loop: "{{ (dcron_crontasks_dir + '/hourly_*.j2') | fileglob }}"

- name: Template all Daily tasks
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/periodic/daily/{{ item | basename | splitext | first }}"
    owner: root
    group: root
    mode: "0700"
  loop: "{{ (dcron_crontasks_dir + '/daily_*.j2') | fileglob }}"

- name: Template all Weekly tasks
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/periodic/weekly/{{ item | basename | splitext | first }}"
    owner: root
    group: root
    mode: "0700"
  loop: "{{ (dcron_crontasks_dir + '/weekly_*.j2') | fileglob }}"

- name: Template all monthly tasks
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/periodic/monthly/{{ item | basename | splitext | first }}"
    owner: root
    group: root
    mode: "0700"
  loop: "{{ (dcron_crontasks_dir + '/monthly_*.j2') | fileglob }}"

- name: Start and enable dcron service
  ansible.builtin.service:
    name: dcron
    state: restarted
    enabled: true
    runlevel: boot

- name: Update crontabs file
  ansible.builtin.command:
    argv:
      - crontab
      - -u
      - root
      - /tmp/crontabs
  register: dcron_crontabs_result
  changed_when: "dcron_crontabs_result.rc != 0"
