---
- name: Gateway Setup
  hosts: gateway
  become: true

  vars:
    wan_iface: wlan0
    lan_iface: eth0
    resources: ../../resources

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ gateway_hostname }}"
        use: alpine
      notify: Reboot system

    - name: Install nftables
      ansible.builtin.package:
        name: nftables
        state: present

    - name: Enable IPv4 forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        sysctl_set: true
        reload: true

    - name: Template nftables rules
      ansible.builtin.template:
        src: "{{ resources }}/gateway/gateway.nft.j2"
        dest: /etc/nftables.d/gateway.nft
        mode: "0644"
      notify: Reload nftables

    - name: Template network interfaces
      ansible.builtin.template:
        src: "{{ resources }}/gateway/interfaces.j2"
        dest: /etc/network/interfaces
        mode: "0644"

    - name: Template eth-watch script
      ansible.builtin.template:
        src: "{{ resources }}/gateway/eth-watch.sh.j2"
        dest: /usr/local/bin/eth-watch.sh
        owner: root
        group: root
        mode: "0500"

    - name: Template eth-watch service file
      ansible.builtin.template:
        src: "{{ resources }}/gateway/eth-watch.j2"
        dest: /etc/init.d/eth-watch
        owner: root
        group: root
        mode: "0755"

    - name: Enable eth-watch at boot
      ansible.builtin.service:
        name: eth-watch
        enabled: true
        state: started

    - name: Enable nftables at boot
      ansible.builtin.service:
        name: nftables
        enabled: true
        state: started

    - name: Enable networking at boot
      ansible.builtin.service:
        name: networking
        enabled: true
        state: started

  handlers:
    - name: Reload nftables
      ansible.builtin.service:
        name: nftables
        state: reloaded

    - name: Reboot system
      ansible.builtin.reboot:

- name: Installing and Configuring tailscale
  import_playbook: tailscale_pb.yml
