---
- name: "Create {{ stacks_dir }}/immich"
  ansible.builtin.file:
    name: "{{ stacks_dir }}/immich"
    state: directory
    owner: "{{ stacks_owner }}"
    group: "{{ stacks_group }}"
    mode: "750"

- name: Fetch the docker compose file
  ansible.builtin.get_url:
    url: "{{ immich_compose_file_url }}"
    dest: "{{ stacks_dir }}/immich/docker-compose.yml"
    owner: "{{ stacks_owner }}"
    group: "{{ stacks_group }}"
    mode: "700"

- name: Add external volumes to immich server
  ansible.builtin.lineinfile:
    path: "{{ stacks_dir }}/immich/docker-compose.yml"
    insertafter: "^\\s{6}- /etc/localtime:/etc/localtime:ro$"
    line: "      - {{ item.value['host'] }}:{{ item.value['dest'] }}{{ item.value['flags'] }}"
    state: present
  loop: "{{ immich_volumes | dict2items }}"

- name: Add PICMEDIA group to immich server
  ansible.builtin.blockinfile:
    path: "{{ stacks_dir }}/immich/docker-compose.yml"
    insertafter: "^\\s*container_name:\\s*immich_server\\s*$"
    block: |2
          group_add:
            - "${PICMEDIA_GID}"
    state: present

- name: Template in .env
  ansible.builtin.template:
    src: "{{ env_template }}"
    dest: "{{ stacks_dir }}/immich/.env"
    owner: root
    group: root
    mode: "700"

- name: Start immich service
  community.docker.docker_compose_v2:
    project_name: immich
    project_src: "{{ stacks_dir }}/immich"
    state: present
  register: docker_output

- name: Show results
  ansible.builtin.debug:
    var: docker_output

- name: Shut immich down
  community.docker.docker_compose_v2:
    project_src: "{{ stacks_dir }}/immich"
    state: stopped
  when: shutdown | bool
