---
# # Docker Volumes ##
immich_volumes:
  pic:
    host: "{{ server_external_dirs['pic']['path'] }}"
    dest: "{{ server_external_dirs['pic']['path'] }}"
    flags: ":ro"

jellyfin_volumes:
  config:
    host: "{{ server_internal_dirs['jellyfin_srv_config_dir']['path'] }}"
    dest: /config
    flags: ""
  cache:
    host: "{{ server_internal_dirs['jellyfin_srv_cache_dir']['path'] }}"
    dest: /cache
    flags: ""
  vid:
    host: "{{ server_external_dirs['vid']['path'] }}"
    dest: /vid
    flags: ":ro"

navidrome_volumes:
  data:
    host: "{{ server_internal_dirs['navidrome_srv_dir']['path'] }}"
    dest: /data
    flags: ""
  musid:
    host: "{{ server_external_dirs['music_tagged']['path'] }}"
    dest: /music
    flags: ":ro"
