---
# # ZFS options ##

# # MAKE SURE THESE ARE CORRECT DRIVES ##
zfs_pool_devices: "{{ ['sdb', 'sdc', 'sdd', 'sde'] if debug | bool else ['sda', 'sdb'] }}"

zfs_pool_name: data
zfs_pool_mountpoint: "{{ external_mount }}"
zfs_pool_mode:
zfs_pool_state: present
zfs_pool_options:
  - "ashift=12"
zfs_boot_services:
  - zfs-import
  - zfs-mount
  - zfs-load-key
zfs_default_services:
  - zfs-zed
