---
- name: Create navidrome stacks dir
  ansible.builtin.file:
    name: "{{ stacks_dir }}/navidrome"
    state: directory
    owner: "{{ stacks_owner }}"
    group: "{{ stacks_group }}"
    mode: "0750"

- name: Template in docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ stacks_dir }}/navidrome/docker-compose.yml"
    owner: "{{ stacks_owner }}"
    group: "{{ stacks_owner }}"
    mode: "0700"

- name: Template in .env
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ stacks_dir }}/navidrome/.env"
    owner: "{{ stacks_owner }}"
    group: "{{ stacks_owner }}"
    mode: "0700"

- name: Add external volumes to navidrome server
  ansible.builtin.lineinfile:
    path: "{{ stacks_dir }}/navidrome/docker-compose.yml"
    insertafter: "^\\s{4}volumes:$"
    line: "      - {{ item.value['host'] }}:{{ item.value['dest'] }}{{ item.value['flags'] }}"
    state: present
  loop: "{{ navidrome_volumes | dict2items }}"

- name: Start the navidrome service
  community.docker.docker_compose_v2:
    project_name: navidrome
    project_src: "{{ stacks_dir }}/navidrome"
    state: present
    pull: always
  register: navidrome_docker_output

- name: Show results
  ansible.builtin.debug:
    var: navidrome_docker_output

- name: Shut navidrome down
  community.docker.docker_compose_v2:
    project_src: "{{ stacks_dir }}/navidrome"
    state: stopped
  when: debug | bool
