---
- name: Install openresolv
  ansible.builtin.package:
    name: openresolv
    state: present
    update_cache: true

- name: Install tailscale
  ansible.builtin.package:
    name: tailscale
    state: present
    update_cache: true

- name: Enable and start Tailscale service
  ansible.builtin.service:
    name: tailscale
    state: started
    enabled: true

- name: Get Tailscale Ping Result
  ansible.builtin.shell: |
    set -o pipefail
    tailscale ping {{ tailscale_control_address | quote }}
  register: tailscale_ping
  changed_when: tailscale_ping.rc != 0

- name: Print Tailscale Ping Result
  ansible.builtin.debug:
    msg: "Tailscale Ping Result: {{ tailscale_ping.stdout }}"
  when: debug | bool

- name: Start and confirm Tailscale
  when: '"pong" not in tailscale_ping.stdout'
  block:
    - name: Bring Tailscale up
      ansible.builtin.command: >
        tailscale up
        --authkey={{ gateway_ts_key | trim }}
        {# without --reset tailscale does not allow us to change flags #}
        --reset
      register: tailscale_output
      changed_when: tailscale_output.rc == 0

    - name: Wait a few seconds
      ansible.builtin.wait_for:
        timeout: 10

    - name: Get Tailscale Ping Result
      ansible.builtin.shell: |
        set -o pipefail
        tailscale ping {{ tailscale_control_address | quote }}
      register: tailscale_ping_new
      changed_when: tailscale_ping_new.rc != 0

    - name: Print Tailscale Ping Result
      ansible.builtin.debug:
        msg: "Tailscale Ping Result: {{ tailscale_ping_new.stdout }}"
      when: debug | bool

    - name: See if Tailscale is up
      ansible.builtin.assert:
        that: '"pong" in tailscale_ping_new.stdout'
        fail_msg: Tailscale is NOT up!
        success_msg: Tailscale is up!
