---
- name: Install and Configure Anki Sync Server
  hosts: server
  become: true

  vars:
    env_template: ../../resources/anki/env.sh.j2
    service_template: ../../resources/anki/anki.sh.j2

  tasks:
    - name: Ensure /srv/anki
      ansible.builtin.file:
        name: /srv/anki
        state: directory
        owner: anki
        group: anki
        mode: "750"

    - name: Ensure /etc/anki
      ansible.builtin.file:
        name: /etc/anki
        state: directory
        owner: anki
        group: anki
        mode: "700"

    - name: Template in service env
      ansible.builtin.template:
        src: "{{ env_template }}"
        dest: /etc/conf.d/anki
        owner: root
        group: root
        mode: "550"

    - name: Template in service file
      ansible.builtin.copy:
        src: "{{ service_template }}"
        dest: /etc/init.d/anki
        owner: root
        group: root
        mode: "550"

    - name: Install Anki
      ansible.builtin.package:
        name: anki
        state: present

    - name: Make sure Anki daemon is running
      ansible.builtin.service:
        name: anki
        state: started
        enabled: true
