---
- name: Installing Beets
  hosts: server
  become: true

  vars:
    config_template: ../../resources/beets/config.yml.j2
    build_constraints_file: ../../resources/beets/build-constraints.txt
    deps:
      - py3-pip
      - python3-dev
      - gstreamer
      - build-base
      - cmake
      - llvm20-dev
      - llvm20-static
      - llvm20-gtest

  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ deps }}"

    - name: Copy in build-constraints
      ansible.builtin.copy:
        src: "{{ build_constraints_file }}"
        dest: /tmp/build-constraints.txt
        mode: "600"

    - name: Install pip in virtual env
      ansible.builtin.pip:
        name: pip
        virtualenv: /opt/beets/venv
        virtualenv_command: "python3 -m venv"
        version: "{{ pip_version }}"
        state: present

    - name: Ensure /home/[main_user]/.config/beets
      ansible.builtin.file:
        name: "/home/{{ main_user }}/.config/beets"
        state: directory
        owner: "{{ main_user }}"
        group: "{{ main_user }}"
        mode: "700"

    - name: Template the beets config
      ansible.builtin.template:
        src: "{{ config_template }}"
        dest: "/home/{{ main_user }}/.config/beets/config.yaml"
        owner: "{{ main_user }}"
        group: "{{ main_user }}"
        mode: "700"

    - name: Install beets
      ansible.builtin.pip:
        name: beets[fetchart,chroma]
        extra_args: --build-constraint /tmp/build-constraints.txt
        virtualenv: /opt/beets/venv
        virtualenv_command: "python3 -m venv"
        state: present

    - name: Remove build constraints
      ansible.builtin.file:
        name: "/tmp/build-constraints.txt"
        state: absent
