---
- name: Install and Configure Navidrome
  hosts: server
  become: true

  vars:
    compose_file: ../../resources/navidrome/docker-compose.yml
    env_template: ../../resources/navidrome/.env.j2

  tasks:
    - name: Create /srv/navidrome
      ansible.builtin.file:
        name: /srv/navidrome
        state: directory
        owner: navidrome
        group: navidrome
        mode: "750"

    - name: "Create [docker_compose_dir]/navidrome"
      ansible.builtin.file:
        name: "{{ docker_compose_dir }}/navidrome"
        state: directory
        owner: root
        group: stacks
        mode: "750"

    - name: Copy in docker-compose.yml
      ansible.builtin.copy:
        src: "{{ compose_file }}"
        dest: "{{ docker_compose_dir }}/navidrome/docker-compose.yml"
        owner: root
        group: root
        mode: "700"

    - name: Template in .env
      ansible.builtin.template:
        src: "{{ env_template }}"
        dest: "{{ docker_compose_dir }}/navidrome/.env"
        owner: root
        group: root
        mode: "700"

    - name: Start the navidrome service
      community.docker.docker_compose_v2:
        project_name: navidrome
        project_src: "{{ docker_compose_dir }}/navidrome"
        state: present
        pull: always
      register: docker_output

    - name: Show results
      ansible.builtin.debug:
        var: docker_output

    - name: Shut navidrome down
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_dir }}/navidrome"
        state: stopped
      when: debug | bool
