---
- name: Install and Configure qbittorrent
  hosts: server
  become: true

  vars:
    compose_file: ../../resources/qbittorrent/docker-compose.yml
    env_template: ../../resources/qbittorrent/.env.j2

    qbittorrent_config_dir: /srv/qbittorrent

  tasks:
    - name: Attempt to add tun module
      block:
        - name: First attempt to add the tun module
          community.general.modprobe:
            name: tun
            state: present
            persistent: present
      rescue:
        - name: Couldn't add the tun module, rebooting
          ansible.builtin.reboot:
            reboot_timeout: 120
        - name: Second attempt to add the tun module
          community.general.modprobe:
            name: tun
            state: present
            persistent: present

    - name: Create [qbittorrent_config_dir]
      ansible.builtin.file:
        name: "{{ qbittorrent_config_dir }}"
        state: directory
        owner: qbittorrent
        group: qbittorrent
        mode: "750"

    - name: "Create [docker_compose_dir]/qbittorrent"
      ansible.builtin.file:
        name: "{{ docker_compose_dir }}/qbittorrent"
        state: directory
        owner: root
        group: stacks
        mode: "750"

    - name: Copy in docker-compose.yml
      ansible.builtin.copy:
        src: "{{ compose_file }}"
        dest: "{{ docker_compose_dir }}/qbittorrent/docker-compose.yml"
        owner: root
        group: root
        mode: "700"

    - name: Template in .env
      ansible.builtin.template:
        src: "{{ env_template }}"
        dest: "{{ docker_compose_dir }}/qbittorrent/.env"
        owner: root
        group: root
        mode: "700"

    - name: Start the qbittorrent service
      community.docker.docker_compose_v2:
        project_name: qbittorrent
        project_src: "{{ docker_compose_dir }}/qbittorrent"
        state: present
      register: docker_output

    - name: Show results
      ansible.builtin.debug:
        var: docker_output

    - name: Read qBittorrent logs
      ansible.builtin.command:
        cmd: docker compose logs
      args:
        chdir: "{{ docker_compose_dir }}/qbittorrent"
      register: qbittorrent_logs
      changed_when: false

    - name: Extract all matching password lines
      ansible.builtin.set_fact:
        qbittorrent_password_lines: >-
          {{
            qbittorrent_logs.stdout
            | regex_findall('^.*temporary.*$', multiline=True)
          }}

    - name: Save the last matching password line to localhost
      ansible.builtin.copy:
        dest: "qbittorrent-temp-password-line.txt"
        mode: "0600"
        content: >-
          {{ qbittorrent_password_lines[-1] if qbittorrent_password_lines | length > 0 else 'NOT FOUND' }}
      delegate_to: localhost
      become: false

    - name: Shut qbittorrent down
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_dir }}/qbittorrent"
        state: stopped
      when: debug | bool
